// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace HospiceToolsChallenge.Infra.Entities;

public partial class ColorDb
{
    public Guid Id { get; set; }

    public string Name { get; set; } = null!;

    public string HexCode { get; set; } = null!;

    public virtual ICollection<PatientDb> PatientDb { get; set; } = new List<PatientDb>();
}